### ISSUE TITLE
The backend crashes when more than one client is connected and they disconnect 

### ISSUE THREAD

**Issue by Leofaber** [Leofaber/PiWeatherStation#2]

**Comment by Leofaber** [comment]
PiWeatherStation app disconnected
/home/pi/PiWeatherStation/node_server/redis_utils.js:16
  redis_client_pubsub.unsubscribe(channel);
                      ^

TypeError: Cannot read property 'unsubscribe' of null
    at Object.unsubscribe_to_data_stream (/home/pi/PiWeatherStation/node_server/redis_utils.js:16:23)
    at Socket.<anonymous> (/home/pi/PiWeatherStation/node_server/index.js:29:19)
    at Socket.emit (events.js:198:13)
    at Socket.emit (/home/pi/PiWeatherStation/node_server/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (/home/pi/PiWeatherStation/node_server/node_modules/socket.io/lib/socket.js:454:8)
    at Client.onclose (/home/pi/PiWeatherStation/node_server/node_modules/socket.io/lib/client.js:254:24)
    at Socket.emit (events.js:203:15)
    at Socket.onClose (/home/pi/PiWeatherStation/node_server/node_modules/engine.io/lib/socket.js:318:10)
    at Object.onceWrapper (events.js:286:20)
    at WebSocket.emit (events.js:198:13)

**Comment by Leofaber** [comment]
events.js:174
      throw er; // Unhandled 'error' event
      ^
AbortError: UNSUBSCRIBE can't be processed. The connection is already closed.
    at handle_offline_command (/home/pi/PiWeatherStation/node_server/node_modules/redis/index.js:779:15)
    at RedisClient.internal_send_command (/home/pi/PiWeatherStation/node_server/node_modules/redis/index.js:813:9)
    at RedisClient.unsubscribe (/home/pi/PiWeatherStation/node_server/node_modules/redis/lib/individualCommands.js:475:17)
    at Object.unsubscribe_to_data_stream (/home/pi/PiWeatherStation/node_server/redis_utils.js:16:23)
    at Socket.<anonymous> (/home/pi/PiWeatherStation/node_server/index.js:29:19)
    at Socket.emit (events.js:198:13)
    at Socket.emit (/home/pi/PiWeatherStation/node_server/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (/home/pi/PiWeatherStation/node_server/node_modules/socket.io/lib/socket.js:454:8)
    at Client.onclose (/home/pi/PiWeatherStation/node_server/node_modules/socket.io/lib/client.js:254:24)
    at Socket.emit (events.js:203:15)
Emitted 'error' event at:
    at callbackOrEmit (/home/pi/PiWeatherStation/node_server/node_modules/redis/lib/utils.js:91:14)
    at /home/pi/PiWeatherStation/node_server/node_modules/redis/lib/utils.js:107:13
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by Leofaber** [comment]
Closed by cf7c336468c56e3f43e3642e873761e219224891
